CREATE TABLE IF NOT EXISTS bio (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(127),
  headline VARCHAR(255),
  about TEXT,
  available ENUM('ready','busy','offline'),
  cv_file VARCHAR(511) NULL,
  updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  active TINYINT(1) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS projects (
  id CHAR(36) DEFAULT (UUID()) PRIMARY KEY,
  title VARCHAR(255),
  slug VARCHAR(255) UNIQUE,
  description LONGTEXT,
  tags JSON,
  github_url VARCHAR(511) NULL,
  live_url VARCHAR(511) NULL,
  thumbnail VARCHAR(511) NULL,
  featured TINYINT(1) DEFAULT 0,
  year YEAR,
  order_index INT DEFAULT 0,
  created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS skills (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(127),
  category VARCHAR(127),
  proficiency TINYINT UNSIGNED DEFAULT 50,
  order_index INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS qualifications (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  institution VARCHAR(127),
  qualification VARCHAR(255),
  grade VARCHAR(127),
  year YEAR,
  order_index INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS posts (
  id CHAR(36) DEFAULT (UUID()) PRIMARY KEY,
  title VARCHAR(255),
  slug VARCHAR(255) UNIQUE,
  excerpt TEXT,
  body LONGTEXT,
  tags JSON,
  thumbnail VARCHAR(511) NULL,
  featured TINYINT(1) DEFAULT 0,
  year YEAR,
  order_index INT DEFAULT 0,
  published TINYINT(1) DEFAULT 0,
  published_on DATETIME NULL,
  created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
